# Generated by Django 4.0.5 on 2022-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('color_list', models.JSONField()),
                ('pattern_list', models.JSONField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
