# Generated by Django 4.0.5 on 2022-06-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='col_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pattern',
            name='row_length',
            field=models.IntegerField(default=0),
        ),
    ]
