# Generated by Django 4.0.5 on 2022-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_modify_date_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
