# Generated by Django 4.0.5 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_pattern_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforpost',
            name='content',
            field=models.TextField(max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='comment',
            field=models.TextField(max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
    ]
