# Generated by Django 4.0.5 on 2022-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwikipost',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wikipost',
            old_name='title',
            new_name='name',
        ),
    ]
