# Generated by Django 4.0.5 on 2022-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_historicalwikipost_changed_by_wikipost_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwikipost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wikipost',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicalwikipost',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
