# Generated by Django 4.0.5 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_historicalwikipost_id_remove_wikipost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwikipost',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalwikipost',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=''),
        ),
    ]
